# Actividad 21 Arreglos 
-  Jorge Emiliano Pomar 
-  A01709338
-  11/03/2025

In [39]:
import numpy as np

# Ejercicios 


        Genere un arreglo de Numpy de puros ceros de tipo de dato "int" de 30 elementos. Imprime el arreglo.




In [40]:
np.zeros(30, dtype=int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

        Genere un arreglo de Numpy con 40 elementos de tipo float sin inicializar. Usa la función empty. Imprime el arreglo.


In [41]:
np.empty(40, dtype=float)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

        Genere un arreglo de Numpy con números que vayan del 10 al 20. Usa la función arange(). Imprime el arreglo.


In [42]:
np.arange(10, 21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

        Genere un arreglo de Numpy con números entre 1 y 30 con incrementos de 4, es decir: [1 5 9....]. Usa la función arange(). Imprime el arreglo.


In [43]:
np.arange(10, 31, 4)

array([10, 14, 18, 22, 26, 30])

        Genere un arreglo de Numpy con 10 elementos de tipo float entre 10 y 30 igualmente espaciados. Usa la función linspace. Imprime el arreglo.


In [44]:
a = np.linspace(10, 30, 10, retstep=True)
print(a)

(array([10.        , 12.22222222, 14.44444444, 16.66666667, 18.88888889,
       21.11111111, 23.33333333, 25.55555556, 27.77777778, 30.        ]), 2.2222222222222223)


        Genera un arreglo de Numpy llamado arreglo1 con 6 números aleatorios enteros entre 5 y 15  y genera otro arreglo llamado arreglo2 con 8 números aleatorios enteros entre 30 y 50. Concatena ambos arreglos en un arreglo llamado arreglo3. Imprime los tres arreglos.

In [45]:
arreglo1 = np.random.randint(5, 16, 6)
print("Arreglo 1: ", arreglo1)

arreglo2 = np.random.randint(30, 51, 8)
print("Arreglo 2: ", arreglo2)

arreglo3 = np.append(arreglo1, arreglo2)
print("Arreglo 3: ", arreglo3)

Arreglo 1:  [13 15 10 14 14 15]
Arreglo 2:  [31 46 31 41 50 33 45 45]
Arreglo 3:  [13 15 10 14 14 15 31 46 31 41 50 33 45 45]


## Ejercicios con funciones

### Ejercicio 1

Crea la función suma_impares que recibe un arreglo de números enteros. Utiliza el ciclo for para recorrer todo el arreglo. La función regresa la suma de todos los elementos impares del arreglo.


In [46]:
def suma_impares(arreglo):
    suma = 0
    for i in arreglo:
        if i % 2 != 0:
            suma += i
    return suma

def main():
    arreglo = np.random.randint(-5, 12, 10)
    print("Arreglo numpy: ", arreglo)
    print(suma_impares(arreglo))

main()

Arreglo numpy:  [-2  0  4 11 10  0  8  8 11 -4]
22


### Ejercicio 2

Crea la función multiplica_arreglo que recibe un arreglo de números enteros y un valor entero x. La función debe de multiplicar cada localidad del arreglo por x y el resultado de la multiplicación asignarla a su respectiva casilla. Utiliza el ciclo for para recorrer todo el arreglo.


In [47]:
def multiplica_arreglo(arreglo, x):
    for i in range(len(arreglo)):
        arreglo[i] *= x
    return arreglo

def main():
    arreglo = np.random.randint(-5, 12, 10)
    print("Arreglo numpy: ", arreglo)
    num_entero = int(input("Ingrese un número entero: "))
    print("Número entero: ", num_entero)
    print(multiplica_arreglo(arreglo, num_entero))

main()

Arreglo numpy:  [11 -1 -5 -1  9  4  1  5  5  4]
Número entero:  4
[ 44  -4 -20  -4  36  16   4  20  20  16]


### Ejercicio 3

Crea la función cuenta_multiplos que recibe un arreglo de números enteros y un valor entero x. La función deberá regresar el resultado de contar todos los elementos múltiplos de x contenidos en el arreglo. NOTA: Los valores negativos no son contemplados. Utiliza el ciclo for para recorrer todo el arreglo.


In [48]:
def cuenta_multiplos(arreglo, x):
    contador = 0
    for i in arreglo:
        if i % x == 0 and i > 0:
            contador += 1
    return contador

def main():
    arreglo = np.random.randint(-5, 12, 10)
    print("Arreglo numpy: ", arreglo)
    num_entero = int(input("Ingrese un número entero: "))
    print("Número entero: ", num_entero)
    print("Múltiplos en el arreglo: ", cuenta_multiplos(arreglo, num_entero))

main()

Arreglo numpy:  [-3 10 11  0  6 11  4 -2 10  1]
Número entero:  2
Múltiplos en el arreglo:  4
